# Generated by Django 2.2 on 2020-05-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birth_date', models.DateField(blank=True)),
                ('age', models.IntegerField()),
                ('months_as_customer', models.IntegerField()),
                ('policy_number', models.IntegerField()),
                ('policy_deductable', models.IntegerField()),
                ('policy_annual_premium', models.IntegerField()),
                ('umbrella_limit', models.IntegerField()),
                ('insured_zip', models.IntegerField()),
                ('insured_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('insured_education_level', models.CharField(max_length=255)),
                ('insured_occupation', models.CharField(max_length=255)),
                ('insured_hobbies', models.CharField(max_length=255)),
                ('insured_relationship', models.CharField(max_length=255)),
                ('capital_gains', models.IntegerField()),
                ('capital_loss', models.IntegerField()),
                ('incident_type', models.CharField(max_length=255)),
                ('collision_type', models.CharField(max_length=255)),
                ('incident_severity', models.CharField(max_length=255)),
                ('authorities_contacted', models.CharField(max_length=255)),
                ('incident_hour_of_the_day', models.IntegerField()),
                ('number_of_vehicles_involved', models.IntegerField()),
                ('property_damage', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('bodily_injuries', models.IntegerField()),
                ('witnesses', models.IntegerField()),
                ('police_report_available', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('total_claim_amount', models.IntegerField()),
                ('injury_claim', models.IntegerField()),
                ('property_claim', models.IntegerField()),
                ('vehicle_claim', models.IntegerField()),
                ('auto_make', models.CharField(max_length=255)),
                ('auto_year', models.IntegerField()),
            ],
        ),
    ]
